### ISSUE TITLE
Which scripts are recommended and supported?

### ISSUE THREAD

**Issue by lecorguille** [genouest/biomaj-data#1]
@abretaud 
As I told you, I want to jump to biomaj3 and since you propose this repository with the community contribution, I was wondering which of them can be considered as standard (at least in your lab).
Until now we used the Migale one in perl 😞 Thus, with the rebuild of our Biomaj instance, I like to use the more supported post-process script. 

You answered me in an email:
- conversion fasta -> la plupart du temps fastacmd.sh, parfois fastacmdTLSE.pl (sans doute pas de raison particulière, juste historique)
- indexation blast -> makeblastdb.sh
- indexation bowtie -> on ne fait pas
- indexation bowtie2 -> bowtie2-build.sh
- indexation bwa -> bwa.sh
- indexation diamond -> index_diamond.sg
- indexation picard -> on ne fait pas
- indexation emboss -> migale/build_emboss.pl
- indexation SRS -> on ne fait pas
- indexation 2bit -> 2bit.sh

**Comment by lecorguille** [comment]
Sorry  but I can't find fastacmd.sh, is it hidden somewhere in this repo?

**Comment by lecorguille** [comment]
I tried to use makeblastdb.sh but it seems that there is no more those symlink: current, future_release in biomaj3. Or I missed something?
https://github.com/genouest/biomaj-data/blob/master/process/makeblastdb.sh#L68

**Comment by abretaud** [comment]
Hi
I just pushed fastacmd.sh: 2a2b80f6bf71a0bc9510d2b35d891044a19ffa0a
For makeblastdb.sh, it works with biomaj3, so I guess the future_release and current dirs still exist, unless there is a specific config at genouest, what do you think @osallou?

**Comment by osallou** [comment]
current is created when release is published.
future_release still exists but only during the update run, it is deleted
after run (ok or ko)

Le lun. 8 août 2016 11:54, Anthony Bretaudeau notifications@github.com a
écrit :
